version: "3.9"

services:
  local-configurator:
    build:
      context: ./local-configurator
      dockerfile: Dockerfile
    container_name: local-configurator
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - DOCKER_HOST=TARGET_IP
    env_file:
      - .env
    networks:
      - nervctf-net

networks:
  nervctf-net:
    driver: bridge
