version: "3.9"

services:
  nervctf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remote-monitor
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - REMOTE_MONITOR_PORT=33133
    
    networks:
      - remote-monitor-net

networks:
  nervctf-net:
    driver: bridge
