version: "3.8"

services:
  local-configurator:
    build: .
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - CTFD_URL=${CTFD_URL}
      - CTFD_API_KEY=${CTFD_API_KEY}
    volumes:
      - ./challenges:/app/challenges
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
