---
- hosts: ctfd
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    docker_user: docker
    #ctfd_path: "{{ lookup('env', 'CTFD_PATH') }}"
    webhook_plugin_repo: https://github.com/iosifache/ctfd-solve-webhook-plugin.git
    containers_plugin_repo: https://github.com/Bigyls/CTFdDockerContainersPlugin.git
    vpn_ip: "{{ ansible_host }}"
    webhook_url: "http://{{ ansible_host }}/webhook-endpoint"
    #ssh_key: "{{ lookup('env', 'SSH_PUBKEY_PATH') }}"
    remote_auth_keys: "/home/{{ docker_user }}/.ssh/authorized_keys"

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
      listen: "systemd reload"

    - name: restart docker
      systemd:
        name: docker
        state: restarted
      listen: "restart docker"

  tasks:
    # Docker installation tasks (rootless)
    - name: Check if Docker group exists
      command: grep -q docker /etc/group
      register: docker_group_exists
      changed_when: false
      ignore_errors: yes

    - name: Install Docker prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes
      when: not docker_group_exists.rc == 0
      tags: [docker_dependencies]

    - name: Create Docker apt keyrings directory
      shell: install -m 0755 -d /etc/apt/keyrings
      when: not docker_group_exists.rc == 0
      tags: [docker_keyrings]

    - name: Download Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      when: not docker_group_exists.rc == 0
      tags: [docker_gpg]

    - name: Set permissions on Docker GPG key
      shell: chmod a+r /etc/apt/keyrings/docker.asc
      when: not docker_group_exists.rc == 0
      tags: [docker_gpg]

    - name: Add Docker repository to apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      when: not docker_group_exists.rc == 0
      tags: [docker_repo]

    - name: Update apt cache
      apt:
        update_cache: yes
      when: not docker_group_exists.rc == 0
      tags: [docker_update]

    - name: Install Docker packages for rootless mode
      apt:
        name:
          - uidmap
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: not docker_group_exists.rc == 0
      tags: [docker_install]

    - name: Run dockerd-rootless-setuptool.sh
      shell: /usr/bin/dockerd-rootless-setuptool.sh install
      when: not docker_group_exists.rc == 0
      tags: [docker_rootless]

    - name: Ensure docker group exists
      group:
        name: docker
        state: present
      when: not docker_group_exists.rc == 0
      tags: [docker_group]

    # Docker user tasks
    - name: Check if docker user exists
      command: id -u {{ docker_user }}
      register: docker_user_exists
      changed_when: false
      ignore_errors: yes

    - name: Create docker user
      user:
        name: "{{ docker_user }}"
        groups: docker
        shell: /bin/bash
        state: present
        create_home: yes
      when: docker_user_exists.rc != 0
      tags: [docker_user]

    # SSH key tasks
    # Gather the contents of the remote authorized_keys file
    - name: Read remote authorized_keys file
      slurp:
        src: "{{ remote_auth_keys }}"
      register: remote_auth_keys_content
      ignore_errors: yes

    # Check if the selected key is already present
    - name: Check if selected key is present in remote authorized_keys
      set_fact:
        key_already_present: "{{ (remote_auth_keys_content.content | b64decode).split('\n') | select('equalto', (lookup('file', ssh_key) | trim)) | list | length > 0 }}"
      when: remote_auth_keys_content is defined and remote_auth_keys_content.content is defined

    # Add the key only if not present
    - name: Add selected SSH public key to remote authorized_keys if missing
      authorized_key:
        user: "{{ docker_user }}"
        state: present
        key: "{{ lookup('file', ssh_key) }}"
      when: not (key_already_present | default(false))
      tags: [docker_ssh]

    # Terminal configuration
    - name: Check if TERM is set in .bashrc
      command: grep -q 'TERM=xterm' /home/{{ docker_user }}/.bashrc
      register: term_set
      changed_when: false
      ignore_errors: yes

    - name: Ensure .bashrc TERM setting for docker user
      lineinfile:
        path: "/home/{{ docker_user }}/.bashrc"
        line: "TERM=xterm"
        create: yes
        state: present
      when: term_set.rc != 0
      tags: [docker_bashrc]

    # CTFd installation tasks
    - name: Check if CTFd directory is valid
      stat:
        path: "{{ ctfd_path }}/requirements.txt"
      register: ctfd_valid
      tags: [ctfd_check]

    - name: Clone CTFd
      git:
        repo: https://github.com/CTFd/CTFd.git
        dest: "{{ ctfd_path }}"
        version: master
      become_user: "{{ docker_user }}"
      when: not ctfd_valid.stat.exists
      tags: [ctfd_clone]

    - name: Set plugins directory
      set_fact:
        plugin_dir: "{{ ctfd_path }}/CTFd/plugins/"
      tags: [plugin_setup]

    - name: Check if plugins directory exists
      stat:
        path: "{{ ctfd_path }}/CTFd/plugins"
      register: plugins_dir_exists
      tags: [ctfd_plugins_dir]

    - name: Create plugins directory
      file:
        path: "{{ ctfd_path }}/CTFd/plugins"
        state: directory
        owner: "{{ docker_user }}"
        group: docker
        mode: "0755"
      when: not plugins_dir_exists.stat.exists
      tags: [ctfd_plugins_dir]

    # Webhook plugin tasks
    - name: Check if webhook plugin exists
      stat:
        path: "{{ plugin_dir }}/solve-webhook-plugin"
      register: webhook_plugin_stat
      tags: [webhook_check]

    - name: Install webhook plugin
      block:
        - name: Install containers plugin
          command: git clone "{{ webhook_plugin_repo }}" "{{ plugin_dir }}/ctfd-solve-webhook-plugin"
          when: not webhook_plugin_stat.stat.exists

        - name: Move plugin to correct location
          command: "mv {{ plugin_dir }}/ctfd-solve-webhook-plugin/solve-webhook-plugin {{ plugin_dir }}/solve-webhook-plugin"
          become_user: "{{ docker_user }}"

        - name: Remove parent plugin directory
          file:
            path: "{{ ctfd_path }}/CTFd/plugins/ctfd-solve-webhook-plugin"
            state: absent
      when: not webhook_plugin_stat.stat.exists

    - name: Add webhook environment variables to .bashrc
      blockinfile:
        path: "/home/{{ docker_user }}/.bashrc"
        block: |
          SOLVE_WEBHOOK_URL={{ webhook_url }}
          SOLVE_WEBHOOK_LIMIT=3
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Webhook variables"
        insertafter: EOF
        create: yes
      when: not webhook_plugin_stat.stat.exists
      tags: [webhook_config]

    # containers plugin tasks
    - name: Check if containers plugin exists
      stat:
        path: "{{ plugin_dir }}/containers"
      register: containers_plugin_stat
      tags: [containers_check]

    - name: Install containers plugin
      command: git clone "{{ containers_plugin_repo }}" "{{ plugin_dir }}/containers"
      when: not containers_plugin_stat.stat.exists

    - name: Copy docker-compose.yml to CTFd path
      copy:
        src: ./docker-compose.yml
        dest: "{{ ctfd_path }}/docker-compose.yml"
        owner: "{{ docker_user }}"
        group: docker
        mode: "0644"
      tags: [ctfd_plugins_compose]

    - name: Start CTFd Docker containers
      command: docker compose --profile ctfd up --build --detach
      args:
        chdir: "{{ ctfd_path }}"
      become_user: "{{ docker_user }}"
      tags: [ctfd_start]
